# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rbreahna <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/07/18 11:56:17 by rbreahna          #+#    #+#              #
#    Updated: 2016/07/21 21:54:17 by rbreahna         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= ft_display_file
FILE = ft_display_file.c
HEADERS = includes
all:
	gcc -c -I$(HEADERS) -Wall -Wextra -Werror $(FILE)
	gcc ft_display_file.o -o $(NAME)
clean:
	rm -f ft_display_file.o
fclean:
	rm -f ft_display_file.o ft_display_file
